# Generated by Django 5.2.8 on 2025-11-05 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the source (e.g., channel name)', max_length=255)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube Channel'), ('blog', 'Blog'), ('ebook', 'Ebook'), ('rss', 'RSS Feed')], default='youtube', help_text='Type of content source', max_length=20)),
                ('link', models.URLField(help_text='URL to the source (YouTube channel, blog URL, etc.)', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('zh', 'Chinese'), ('es', 'Spanish'), ('de', 'German'), ('other', 'Other')], default='en', help_text='Primary language of the content', max_length=20)),
                ('channel_id', models.CharField(blank=True, help_text='YouTube channel ID (for YouTube sources)', max_length=100, null=True)),
                ('include_shorts', models.BooleanField(default=False, help_text='Include YouTube Shorts when collecting videos (YouTube sources only)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON (e.g., description, tags, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active and being monitored')),
                ('last_collected', models.DateTimeField(blank=True, help_text='Last time content was collected from this source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type'], name='sources_source__65c870_idx'), models.Index(fields=['language'], name='sources_languag_f06f8c_idx'), models.Index(fields=['is_active'], name='sources_is_acti_267b08_idx')],
            },
        ),
    ]
