# Generated by Django 5.2.8 on 2025-11-05 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='External ID (e.g., video_id, blog post slug, etc.)', max_length=255)),
                ('title', models.CharField(help_text='Title of the content', max_length=500)),
                ('link', models.URLField(help_text='URL to the content', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('blog_post', 'Blog Post'), ('ebook', 'Ebook')], default='video', help_text='Type of content', max_length=20)),
                ('date', models.DateField(help_text='Date when content was published/uploaded')),
                ('content', models.TextField(blank=True, help_text='Text content (transcript, article text, etc.)')),
                ('processed', models.BooleanField(default=False, help_text='Whether content has been processed (embedded, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(help_text='Source this content came from', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='sources.source')),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['source'], name='contents_source__cfc144_idx'), models.Index(fields=['external_id'], name='contents_externa_55f31d_idx'), models.Index(fields=['content_type'], name='contents_content_4e46bd_idx'), models.Index(fields=['date'], name='contents_date_f6457b_idx'), models.Index(fields=['processed'], name='contents_process_5d543c_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
