# Generated by Django 5.2.8 on 2025-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='has_content',
            field=models.BooleanField(default=False, help_text='Whether content text is available (automatically set)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='channel_id',
            field=models.CharField(blank=True, help_text='YouTube channel ID (required for YouTube sources)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['has_content'], name='contents_has_con_0885ad_idx'),
        ),
    ]
