# Generated by Django 5.2.8 on 2025-11-08 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_content_has_content_alter_source_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the source (YouTube channel, blog URL, etc.)', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
