# Generated by Django 5.2.8 on 2025-11-08 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_make_link_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the content', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
