# Generated by Django 5.2.8 on 2025-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_make_content_link_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'culture', 'history', 'food')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this tag represents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tags_name_38920e_idx'), models.Index(fields=['slug'], name='tags_slug_c72f9b_idx')],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this content', related_name='contents', to='sources.tag'),
        ),
    ]
