# Generated by Django 5.2.8 on 2025-11-09 09:22

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_tag_content_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Order of this chunk within the content (0-based)')),
                ('text', models.TextField(help_text='Text content of this chunk')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='Vector embedding for semantic search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='Content this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.content')),
            ],
            options={
                'db_table': 'content_chunks',
                'ordering': ['content', 'chunk_index'],
                'indexes': [models.Index(fields=['content', 'chunk_index'], name='content_chu_content_69e279_idx'), models.Index(fields=['embedding'], name='content_chunks_embedding_idx', opclasses=['vector_cosine_ops'])],
                'unique_together': {('content', 'chunk_index')},
            },
        ),
    ]
