# Generated by Django 5.2.8 on 2025-11-09 09:30

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_contentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding for semantic search', null=True),
        ),
        # Create vector index using HNSW for efficient similarity search
        # Now possible because text-embedding-3-small (1536 dims) is under the 2000 limit
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS content_chunks_embedding_idx 
                ON content_chunks 
                USING hnsw (embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64)
                WHERE embedding IS NOT NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS content_chunks_embedding_idx;",
        ),
    ]
