# Generated by Django 5.2.8 on 2025-11-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_alter_contentchunk_embedding'),
    ]

    operations = [
        # Create vector index using HNSW for efficient similarity search
        # Now possible because text-embedding-3-small (1536 dims) is under the 2000 limit
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS content_chunks_embedding_idx 
                ON content_chunks 
                USING hnsw (embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64)
                WHERE embedding IS NOT NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS content_chunks_embedding_idx;",
        ),
    ]
