# Generated by Django 5.2.8 on 2025-11-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_add_vector_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('source_created', 'Source Created'), ('source_updated', 'Source Updated'), ('source_deleted', 'Source Deleted'), ('content_created', 'Content Created'), ('content_updated', 'Content Updated'), ('content_deleted', 'Content Deleted'), ('content_tagged', 'Content Tagged'), ('embeddings_generated', 'Embeddings Generated'), ('tags_created', 'Tags Created'), ('import_completed', 'Import Completed')], help_text='Type of activity', max_length=50)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('user', models.CharField(blank=True, help_text='User who performed the activity (if applicable)', max_length=150, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., count of items processed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, help_text='Related content (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='sources.content')),
                ('source', models.ForeignKey(blank=True, help_text='Related source (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='sources.source')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type'], name='activity_lo_activit_fd7ee5_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'), models.Index(fields=['source'], name='activity_lo_source__5be3ce_idx'), models.Index(fields=['content'], name='activity_lo_content_999073_idx')],
            },
        ),
    ]
