# Generated by Django 5.2.8 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tagging_provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI')], default='ollama', help_text='Default provider for content tagging', max_length=20)),
                ('default_tagging_model', models.CharField(default='gpt-oss:20b-cloud', help_text="Default model for content tagging (e.g., 'gpt-oss:20b-cloud' for Ollama, 'gpt-3.5-turbo' for OpenAI)", max_length=100)),
                ('default_embedding_provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', help_text='Default provider for embeddings', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('source_created', 'Source Created'), ('source_updated', 'Source Updated'), ('source_deleted', 'Source Deleted'), ('content_created', 'Content Created'), ('content_updated', 'Content Updated'), ('content_deleted', 'Content Deleted'), ('content_tagged', 'Content Tagged'), ('embeddings_generated', 'Embeddings Generated'), ('tags_created', 'Tags Created'), ('import_completed', 'Import Completed'), ('settings_updated', 'Settings Updated')], help_text='Type of activity', max_length=50),
        ),
    ]
