# Generated by Django 5.2.8 on 2025-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_settings_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='filter_videos',
            field=models.BooleanField(default=False, help_text='Filter videos using AI to only include videos relevant to China (YouTube sources only)'),
        ),
    ]
