# Generated by Django 5.2.8 on 2025-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_source_filter_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_video_filter_model',
            field=models.CharField(default='gpt-oss:20b-cloud', help_text="Default model for video filtering (e.g., 'gpt-oss:20b-cloud' for Ollama)", max_length=100),
        ),
    ]
