# Generated by Django 5.2.8 on 2025-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_settings_default_video_filter_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='default_video_filter_model',
        ),
        migrations.AlterField(
            model_name='source',
            name='filter_videos',
            field=models.BooleanField(default=False, help_text='Filter videos to only include those relevant to China (YouTube sources only)'),
        ),
    ]
