# Generated by Django 5.2.8 on 2025-11-13 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_add_transcript_content_fetched_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='blog_only',
            field=models.BooleanField(default=False, help_text='Only collect blog posts, exclude other content types (blog sources only)'),
        ),
        migrations.AddField(
            model_name='source',
            name='filter_china',
            field=models.BooleanField(default=False, help_text='Filter blog posts to only include those relevant to China (blog sources only)'),
        ),
        migrations.AddField(
            model_name='source',
            name='sitemap',
            field=models.URLField(blank=True, help_text='Sitemap URL (for blog sources)', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='source',
            name='xml_feed',
            field=models.URLField(blank=True, help_text='RSS/XML feed URL (optional, for blog sources)', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
