# Generated by Django 5.2.8 on 2025-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_add_blog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='ebook_file',
            field=models.FileField(blank=True, help_text='Upload ebook text file (for ebook sources)', null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='source',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Publication date of the ebook (for ebook sources)', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text='Primary language of the content', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube Channel'), ('blog', 'Blog'), ('ebook', 'Ebook')], default='youtube', help_text='Type of content source', max_length=20),
        ),
    ]
