# Generated by Django 5.2.8 on 2025-11-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_source_ebook_file_source_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_filtering_model',
            field=models.CharField(default='llama3.2:latest', help_text="Default Ollama model for filtering content (YouTube videos and blog posts) - e.g., 'llama3.2:latest', 'gpt-oss:20b-cloud'", max_length=100),
        ),
    ]
