# Generated by Django 5.2.8 on 2025-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0018_add_default_filtering_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or topic of the post idea', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the post idea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_ideas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='post_ideas_created_62ee8d_idx')],
            },
        ),
    ]
