# Generated by Django 5.2.8 on 2025-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_postidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('source_created', 'Source Created'), ('source_updated', 'Source Updated'), ('source_deleted', 'Source Deleted'), ('content_created', 'Content Created'), ('content_updated', 'Content Updated'), ('content_deleted', 'Content Deleted'), ('content_tagged', 'Content Tagged'), ('embeddings_generated', 'Embeddings Generated'), ('tags_created', 'Tags Created'), ('import_completed', 'Import Completed'), ('settings_updated', 'Settings Updated'), ('transcript_fetched', 'Transcript Fetched'), ('content_fetched', 'Content Fetched'), ('post_idea_created', 'Post Idea Created'), ('post_idea_updated', 'Post Idea Updated'), ('post_idea_deleted', 'Post Idea Deleted'), ('post_ideas_generated', 'Post Ideas Generated')], help_text='Type of activity', max_length=50),
        ),
    ]
