# Generated by Django 5.2.8 on 2025-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPostIdeaGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable scheduled post idea generation')),
                ('trigger_time', models.TimeField(default='09:00', help_text='Time of day to trigger generation (24-hour format, e.g., 09:00 for 9 AM)')),
                ('num_ideas', models.IntegerField(default=5, help_text='Number of post ideas to generate each time')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], default='ollama', help_text='AI provider to use for generation', max_length=20)),
                ('model', models.CharField(default='gpt-oss:20b-cloud', help_text="Model to use for generation (e.g., 'gpt-oss:20b-cloud' for Ollama, 'gpt-4o-mini' for OpenAI)", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time the scheduled generation was executed', null=True)),
            ],
            options={
                'verbose_name': 'Scheduled Post Idea Generation',
                'verbose_name_plural': 'Scheduled Post Idea Generation',
                'db_table': 'scheduled_post_idea_generation',
            },
        ),
    ]
