# Generated by Django 5.2.8 on 2025-11-30 09:33

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_scheduledpostideageneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='postidea',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding of the title for semantic similarity checking', null=True),
        ),
        # Create vector index using HNSW for efficient similarity search
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS post_ideas_title_embedding_idx 
                ON post_ideas 
                USING hnsw (title_embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64)
                WHERE title_embedding IS NOT NULL;
            """,
            reverse_sql="DROP INDEX IF EXISTS post_ideas_title_embedding_idx;",
        ),
    ]
