# Generated by Django 5.2.8 on 2025-12-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_add_post_idea_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated if not provided)', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Full content of the blog post (HTML or Markdown)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 characters)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing this blog post', related_name='blog_posts', to='sources.tag')),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'), models.Index(fields=['-created_at'], name='blog_posts_created_278ce4_idx')],
            },
        ),
    ]
