# Generated by Django 5.2.8 on 2025-12-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_add_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_idea',
            field=models.ForeignKey(blank=True, help_text='Post idea this blog post was created from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='sources.postidea'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['post_idea'], name='blog_posts_post_id_6f79fd_idx'),
        ),
    ]
