# Generated by Django 5.2.8 on 2025-12-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_add_blog_post_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether this blog post is published'),
        ),
    ]
