# Generated by Django 5.2.8 on 2025-12-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0026_add_blog_post_published'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published'], name='blog_posts_publish_cf864f_idx'),
        ),
    ]
