# Generated by Django 5.2.8 on 2025-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_add_blog_post_published_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='postidea',
            name='primary_keyword',
            field=models.CharField(blank=True, help_text="Primary SEO keyword for this post idea (e.g., 'Chengdu travel guide', 'China visa requirements')", max_length=100),
        ),
    ]
