# Generated by Django 5.2.8 on 2025-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0029_make_primary_keyword_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_posts/featured_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_description',
            field=models.TextField(blank=True, help_text='Description of what the featured image should show (generated during metadata generation)'),
        ),
    ]
