# Generated by Django 5.2.8 on 2025-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0030_add_featured_image_to_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_description',
            field=models.CharField(blank=True, help_text='Alt text for the featured image (concise description, 50-125 characters recommended)', max_length=200),
        ),
    ]
