# Generated by Django 5.2.8 on 2025-12-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0031_change_featured_image_description_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('source_created', 'Source Created'), ('source_updated', 'Source Updated'), ('source_deleted', 'Source Deleted'), ('content_created', 'Content Created'), ('content_updated', 'Content Updated'), ('content_deleted', 'Content Deleted'), ('content_tagged', 'Content Tagged'), ('embeddings_generated', 'Embeddings Generated'), ('tags_created', 'Tags Created'), ('import_completed', 'Import Completed'), ('settings_updated', 'Settings Updated'), ('transcript_fetched', 'Transcript Fetched'), ('content_fetched', 'Content Fetched'), ('post_idea_created', 'Post Idea Created'), ('post_idea_updated', 'Post Idea Updated'), ('post_idea_deleted', 'Post Idea Deleted'), ('post_ideas_generated', 'Post Ideas Generated'), ('blog_post_created', 'Blog Post Created'), ('blog_post_updated', 'Blog Post Updated'), ('blog_post_deleted', 'Blog Post Deleted'), ('blog_post_image_uploaded', 'Blog Post Image Uploaded')], help_text='Type of activity', max_length=50),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text="Original filename or identifier from content (e.g., 'leshan-giant-buddha-river-view.jpg')", max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=200)),
                ('image_file', models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='blog_posts/images/')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is the featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(help_text='Blog post this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sources.blogpost')),
            ],
            options={
                'db_table': 'blog_post_images',
                'indexes': [models.Index(fields=['blog_post', 'filename'], name='blog_post_i_blog_po_a55a67_idx')],
                'unique_together': {('blog_post', 'filename')},
            },
        ),
    ]
