# Generated by Django 5.2.8 on 2025-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0032_add_blog_post_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text="FAQ items as JSON array, each with 'question' and 'answer' fields"),
        ),
    ]
