# Generated by Django 5.2.8 on 2025-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0033_add_faq_to_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faq_title',
            field=models.CharField(blank=True, help_text='Title for the FAQ section displayed on the page', max_length=200),
        ),
    ]
