# Generated by Django 5.2.8 on 2025-12-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_blogpost_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='online_url',
            field=models.URLField(blank=True, help_text='URL of the published blog post on the live website', max_length=500, null=True),
        ),
    ]
